export enum Icons {
  add = 'add',
  listCircle = 'list-circle',
  listCircleOutline = 'list-circle-outline',
  person = 'person',
  cameraOutline = 'camera-outline',
  calendarOutline = 'calendar-outline',
  compassOutline = 'compass-outline',
  readerOutline = 'reader-outline',
  heartOutline = 'heart-outline',
  heartFilled = 'heart',
  checkmarkOutline = 'checkmark-circle-outline',
  checkmarkFilled = 'checkmark-circle',
  arrowBack = 'arrow-back-outline',
  edit = 'create-outline',
  editFilled = 'create',
  delete = 'trash',
  pin = 'pin',
  eyeOff = 'eye-off-outline',
  eyeOn = 'eye-outline',
  logout = 'exit',
  population = 'accessibility-outline',
  currency = 'cash-outline',
  capital = 'golf-outline',
  language = 'chatbubbles-outline',
  location = 'location',
  placesToVisit = 'location-outline',
  search = 'search-outline',
  filter = 'filter-outline',
  menu = 'menu',
  linkOutline = 'link-outline',
  close = 'close',
  remove = 'close-circle-outline',
  save = 'save-outline',
  locate = 'locate-outline',
  map = 'map-outline',
  mapFilled = 'map',
  duration = 'hourglass-outline',
  place = 'home-outline',
  country = 'flag',
  compass = 'compass-outline',
  walk = 'walk',
  bicycle = 'bicycle',
  car = 'car',
  settingsOutline = 'settings-outline',
  settingsFilled = 'settings',
  goTo = 'arrow-forward-circle',
  arrowLeft = 'chevron-back',
  activity = 'flash',
  routePlanner = 'git-merge-outline',
  openDetails = 'caret-down-outline',
  closeDetails = 'caret-up-outline',
  toggle = 'toggle',
}

export enum ButtonMode {
  default = 'default',
  flat = 'flat',
}

export enum ColorScheme {
  neutral = 'neutral',
  primary = 'primary',
  accent = 'accent',
  complementary = 'complementary',
  error = 'error',
}
